-- MySQL Script generated by MySQL Workbench
-- Tue May 12 23:20:56 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bpmmi5qwcmabqrizkvwa
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bpmmi5qwcmabqrizkvwa
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bpmmi5qwcmabqrizkvwa` DEFAULT CHARACTER SET utf8 ;
USE `bpmmi5qwcmabqrizkvwa` ;

-- -----------------------------------------------------
-- Table `bpmmi5qwcmabqrizkvwa`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bpmmi5qwcmabqrizkvwa`.`usuario` (
  `usuId` INT(15) NOT NULL AUTO_INCREMENT,
  `usuNombre` VARCHAR(50) NOT NULL,
  `usuEmail` VARCHAR(75) NOT NULL,
  `usuPassword` VARCHAR(100) NULL,
  `usuEstado` TINYINT(1) NOT NULL DEFAULT 1,
  `usuCreado` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `usuModificado` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  PRIMARY KEY (`usuId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bpmmi5qwcmabqrizkvwa`.`empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bpmmi5qwcmabqrizkvwa`.`empresa` (
  `empId` INT(15) NOT NULL AUTO_INCREMENT,
  `empMarca` VARCHAR(60) NOT NULL,
  `empMatricula` VARCHAR(50) NOT NULL,
  `empRepre` VARCHAR(40) NOT NULL,
  `empImagen` VARCHAR(200) NULL,
  `empCiudad` VARCHAR(45) NOT NULL,
  `empDireccion` VARCHAR(60) NOT NULL,
  `empTelefono` VARCHAR(40) NOT NULL,
  `empCorreo` VARCHAR(70) NOT NULL,
  `empPagina` VARCHAR(200) NULL,
  `empEstado` TINYINT(1) NOT NULL DEFAULT 1,
  `empCreado` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `empModificado` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  `usuario_usuId` INT(15) NOT NULL,
  PRIMARY KEY (`empId`, `usuario_usuId`),
  INDEX `fk_empresa_usuario_idx` (`usuario_usuId` ),
  CONSTRAINT `fk_empresa_usuario`
    FOREIGN KEY (`usuario_usuId`)
    REFERENCES `bpmmi5qwcmabqrizkvwa`.`usuario` (`usuId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bpmmi5qwcmabqrizkvwa`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bpmmi5qwcmabqrizkvwa`.`persona` (
  `perId` INT(15) NOT NULL AUTO_INCREMENT,
  `perNombre` VARCHAR(80) NOT NULL,
  `perEmail` VARCHAR(75) NOT NULL,
  `perRut` VARCHAR(50) NOT NULL,
  `perFoto` VARCHAR(200) NULL,
  `perDireccion` VARCHAR(45) NOT NULL,
  `perCiudad` VARCHAR(20) NOT NULL,
  `perTelefono` VARCHAR(40) NOT NULL,
  `perPagina` VARCHAR(200) NULL,
  `perEstado` TINYINT(1) NOT NULL DEFAULT 1,
  `perCreado` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `perModificado` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  `usuario_usuId` INT(15) NOT NULL,
  PRIMARY KEY (`perId`, `usuario_usuId`),
  INDEX `fk_persona_usuario1_idx` (`usuario_usuId` ),
  CONSTRAINT `fk_persona_usuario1`
    FOREIGN KEY (`usuario_usuId`)
    REFERENCES `bpmmi5qwcmabqrizkvwa`.`usuario` (`usuId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bpmmi5qwcmabqrizkvwa`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bpmmi5qwcmabqrizkvwa`.`cliente` (
  `cliId` INT(15) NOT NULL AUTO_INCREMENT,
  `cliNombre` VARCHAR(40) NOT NULL,
  `cliApellido` VARCHAR(40) NOT NULL,
  `cliCelular` VARCHAR(20) NOT NULL,
  `cliToken` INT(4) NOT NULL DEFAULT 0,
  `cliEstado` TINYINT(1) NOT NULL DEFAULT 1,
  `cliCreado` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `cliModificado` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  `usuario_usuId` INT(15) NOT NULL,
  PRIMARY KEY (`cliId`, `usuario_usuId`),
  INDEX `fk_cliente_usuario1_idx` (`usuario_usuId` ),
  CONSTRAINT `fk_cliente_usuario1`
    FOREIGN KEY (`usuario_usuId`)
    REFERENCES `bpmmi5qwcmabqrizkvwa`.`usuario` (`usuId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bpmmi5qwcmabqrizkvwa`.`proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bpmmi5qwcmabqrizkvwa`.`proveedor` (
  `proId` INT(15) NOT NULL AUTO_INCREMENT,
  `proEmp` TINYINT(1) NOT NULL DEFAULT 0,
  `proActivo` TINYINT(1) NOT NULL DEFAULT 0,
  `proFecha` TIMESTAMP NULL,
  `proEstado` TINYINT(1) NOT NULL DEFAULT 1,
  `proCreado` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `proModificado` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  `usuario_usuId` INT(15) NOT NULL,
  PRIMARY KEY (`proId`, `usuario_usuId`),
  INDEX `fk_proveedor_usuario1_idx` (`usuario_usuId` ),
  CONSTRAINT `fk_proveedor_usuario1`
    FOREIGN KEY (`usuario_usuId`)
    REFERENCES `bpmmi5qwcmabqrizkvwa`.`usuario` (`usuId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bpmmi5qwcmabqrizkvwa`.`proveedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bpmmi5qwcmabqrizkvwa`.`proveedores` (
  `prosId` INT(15) NOT NULL AUTO_INCREMENT,
  `proveedor_proId` INT(15) NOT NULL,
  `proveedor_proId1` INT(15) NULL,
  `proveedor_proId2` INT(15) NULL,
  `proveedor_proId3` INT(15) NULL,
  PRIMARY KEY (`prosId`, `proveedor_proId`),
  INDEX `fk_proveedores_proveedor1_idx` (`proveedor_proId` ),
  INDEX `fk_proveedores_proveedor2_idx` (`proveedor_proId1` ),
  INDEX `fk_proveedores_proveedor3_idx` (`proveedor_proId2` ),
  INDEX `fk_proveedores_proveedor4_idx` (`proveedor_proId3` ),
  CONSTRAINT `fk_proveedores_proveedor1`
    FOREIGN KEY (`proveedor_proId`)
    REFERENCES `bpmmi5qwcmabqrizkvwa`.`proveedor` (`proId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_proveedores_proveedor2`
    FOREIGN KEY (`proveedor_proId1`)
    REFERENCES `bpmmi5qwcmabqrizkvwa`.`proveedor` (`proId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_proveedores_proveedor3`
    FOREIGN KEY (`proveedor_proId2`)
    REFERENCES `bpmmi5qwcmabqrizkvwa`.`proveedor` (`proId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_proveedores_proveedor4`
    FOREIGN KEY (`proveedor_proId3`)
    REFERENCES `bpmmi5qwcmabqrizkvwa`.`proveedor` (`proId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bpmmi5qwcmabqrizkvwa`.`tipoVideo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bpmmi5qwcmabqrizkvwa`.`tipoVideo` (
  `tvidId` INT(15) NOT NULL AUTO_INCREMENT,
  `tvidNombre` VARCHAR(50) NOT NULL,
  `tvidEstado` TINYINT(1) NOT NULL DEFAULT 1,
  `tvidCreado` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `tvidModificado` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  PRIMARY KEY (`tvidId`),
  UNIQUE INDEX `cherCreado_UNIQUE` (`tvidCreado` ))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bpmmi5qwcmabqrizkvwa`.`video`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bpmmi5qwcmabqrizkvwa`.`video` (
  `vidId` INT(15) NOT NULL AUTO_INCREMENT,
  `vidLink` VARCHAR(200) NOT NULL,
  `vidNombre` VARCHAR(80) NOT NULL,
  `vidDescripcion` MEDIUMBLOB NOT NULL,
  `vidPrecio` FLOAT(50) NOT NULL,
  `vidEstado` TINYINT(1) NOT NULL DEFAULT 1,
  `vidCreado` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `vidModificado` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  `cliente_cliId` INT(15) NOT NULL,
  `proveedores_prosId` INT(15) NOT NULL,
  `tipoVideo_tvidId` INT(15) NOT NULL,
  PRIMARY KEY (`vidId`, `cliente_cliId`, `proveedores_prosId`, `tipoVideo_tvidId`),
  INDEX `fk_precio_cliente1_idx` (`cliente_cliId` ),
  INDEX `fk_video_proveedores1_idx` (`proveedores_prosId` ),
  INDEX `fk_video_tipoVideo1_idx` (`tipoVideo_tvidId` ),
  CONSTRAINT `fk_precio_cliente1`
    FOREIGN KEY (`cliente_cliId`)
    REFERENCES `bpmmi5qwcmabqrizkvwa`.`cliente` (`cliId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_video_proveedores1`
    FOREIGN KEY (`proveedores_prosId`)
    REFERENCES `bpmmi5qwcmabqrizkvwa`.`proveedores` (`prosId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_video_tipoVideo1`
    FOREIGN KEY (`tipoVideo_tvidId`)
    REFERENCES `bpmmi5qwcmabqrizkvwa`.`tipoVideo` (`tvidId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bpmmi5qwcmabqrizkvwa`.`chat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bpmmi5qwcmabqrizkvwa`.`chat` (
  `chatId` INT(15) NOT NULL AUTO_INCREMENT,
  `chatMensaje` VARCHAR(200) NOT NULL,
  `chatPregunta` TINYINT(1) NOT NULL DEFAULT 1,
  `chatEstado` TINYINT(1) NOT NULL DEFAULT 1,
  `chatCreado` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `chatModificado` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  `cliente_cliId` INT(15) NOT NULL,
  `proveedores_prosId` INT(15) NOT NULL,
  PRIMARY KEY (`chatId`, `cliente_cliId`, `proveedores_prosId`),
  INDEX `fk_precio_cliente2_idx` (`cliente_cliId` ),
  INDEX `fk_video_proveedores2_idx` (`proveedores_prosId` ),
  CONSTRAINT `fk_precio_cliente2`
    FOREIGN KEY (`cliente_cliId`)
    REFERENCES `bpmmi5qwcmabqrizkvwa`.`cliente` (`cliId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_video_proveedores2`
    FOREIGN KEY (`proveedores_prosId`)
    REFERENCES `bpmmi5qwcmabqrizkvwa`.`proveedores` (`prosId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bpmmi5qwcmabqrizkvwa`.`tipoCargo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bpmmi5qwcmabqrizkvwa`.`tipoCargo` (
  `tcarId` INT(15) NOT NULL AUTO_INCREMENT,
  `tcarNombre` VARCHAR(50) NOT NULL,
  `tcarEstado` TINYINT(1) NOT NULL DEFAULT 1,
  `tcarCreado` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `tcarModificado` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  PRIMARY KEY (`tcarId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bpmmi5qwcmabqrizkvwa`.`cargos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bpmmi5qwcmabqrizkvwa`.`cargos` (
  `carId` INT(15) NOT NULL AUTO_INCREMENT,
  `carNombre` VARCHAR(40) NOT NULL,
  `carImg` VARCHAR(40) NOT NULL,
  `carPrecio` FLOAT(40) NOT NULL,
  `carCalificacion` FLOAT(5) NOT NULL,
  `carCertificacion` TINYINT(1) NOT NULL DEFAULT 0,
  `carEstado` TINYINT(1) NOT NULL DEFAULT 1,
  `carCreado` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `carModificado` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  `tipoCargo_tcarId` INT(15) NOT NULL,
  `proveedor_proId` INT(15) NOT NULL,
  PRIMARY KEY (`carId`, `tipoCargo_tcarId`, `proveedor_proId`),
  INDEX `fk_cargos_tipoCargo1_idx` (`tipoCargo_tcarId` ),
  INDEX `fk_cargos_proveedor1_idx` (`proveedor_proId` ),
  CONSTRAINT `fk_cargos_tipoCargo1`
    FOREIGN KEY (`tipoCargo_tcarId`)
    REFERENCES `bpmmi5qwcmabqrizkvwa`.`tipoCargo` (`tcarId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cargos_proveedor1`
    FOREIGN KEY (`proveedor_proId`)
    REFERENCES `bpmmi5qwcmabqrizkvwa`.`proveedor` (`proId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bpmmi5qwcmabqrizkvwa`.`tipoHerramienta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bpmmi5qwcmabqrizkvwa`.`tipoHerramienta` (
  `therId` INT(15) NOT NULL AUTO_INCREMENT,
  `therNombre` VARCHAR(50) NOT NULL,
  `therEstado` TINYINT(1) NOT NULL DEFAULT 1,
  `therCreado` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `therModificado` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  PRIMARY KEY (`therId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bpmmi5qwcmabqrizkvwa`.`herramientas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bpmmi5qwcmabqrizkvwa`.`herramientas` (
  `herId` INT(15) NOT NULL AUTO_INCREMENT,
  `herNombre` VARCHAR(40) NOT NULL,
  `herImg` VARCHAR(40) NOT NULL,
  `herPrecio` FLOAT(40) NOT NULL,
  `herCertificada` TINYINT(1) NOT NULL DEFAULT 0,
  `herCalificacion` FLOAT(5) NOT NULL,
  `herEstado` TINYINT(1) NOT NULL DEFAULT 1,
  `herCreado` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `herModificado` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  `tipoHerramienta_therId` INT(15) NOT NULL,
  `proveedor_proId` INT(15) NOT NULL,
  PRIMARY KEY (`herId`, `tipoHerramienta_therId`, `proveedor_proId`),
  INDEX `fk_herramientas_tipoHerramienta1_idx` (`tipoHerramienta_therId` ),
  INDEX `fk_herramientas_proveedor1_idx` (`proveedor_proId` ),
  CONSTRAINT `fk_herramientas_tipoHerramienta1`
    FOREIGN KEY (`tipoHerramienta_therId`)
    REFERENCES `bpmmi5qwcmabqrizkvwa`.`tipoHerramienta` (`therId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_herramientas_proveedor1`
    FOREIGN KEY (`proveedor_proId`)
    REFERENCES `bpmmi5qwcmabqrizkvwa`.`proveedor` (`proId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bpmmi5qwcmabqrizkvwa`.`calificacionVideo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bpmmi5qwcmabqrizkvwa`.`calificacionVideo` (
  `cagId` INT(15) NOT NULL AUTO_INCREMENT,
  `cagDescripcion` MEDIUMBLOB NOT NULL,
  `cagCalificacion` FLOAT(5) NOT NULL,
  `cagEstado` TINYINT(1) NOT NULL DEFAULT 1,
  `cagCreado` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `cagModificado` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  `video_vidId` INT(15) NOT NULL,
  PRIMARY KEY (`cagId`, `video_vidId`),
  UNIQUE INDEX `cherCreado_UNIQUE` (`cagCreado` ),
  INDEX `fk_calificacionProveedor_video1_idx` (`video_vidId` ),
  CONSTRAINT `fk_calificacionProveedor_video1`
    FOREIGN KEY (`video_vidId`)
    REFERENCES `bpmmi5qwcmabqrizkvwa`.`video` (`vidId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bpmmi5qwcmabqrizkvwa`.`tokensUsados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bpmmi5qwcmabqrizkvwa`.`tokensUsados` (
  `tokId` INT(15) NOT NULL AUTO_INCREMENT,
  `tokActivo` TINYINT(1) NOT NULL DEFAULT 0,
  `cliente_cliId` INT(15) NOT NULL,
  `proveedor_proId` INT(15) NOT NULL,
  PRIMARY KEY (`tokId`, `cliente_cliId`, `proveedor_proId`),
  INDEX `fk_cliente_has_proveedor_proveedor1_idx` (`proveedor_proId` ),
  INDEX `fk_cliente_has_proveedor_cliente1_idx` (`cliente_cliId` ),
  CONSTRAINT `fk_cliente_has_proveedor_cliente1`
    FOREIGN KEY (`cliente_cliId`)
    REFERENCES `bpmmi5qwcmabqrizkvwa`.`cliente` (`cliId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cliente_has_proveedor_proveedor1`
    FOREIGN KEY (`proveedor_proId`)
    REFERENCES `bpmmi5qwcmabqrizkvwa`.`proveedor` (`proId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bpmmi5qwcmabqrizkvwa`.`videoCargos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bpmmi5qwcmabqrizkvwa`.`videoCargos` (
  `video_vidId` INT(15) NOT NULL,
  `cargos_carId` INT(15) NOT NULL,
  PRIMARY KEY (`video_vidId`, `cargos_carId`),
  INDEX `fk_video_has_cargos_cargos1_idx` (`cargos_carId` ),
  INDEX `fk_video_has_cargos_video1_idx` (`video_vidId` ),
  CONSTRAINT `fk_video_has_cargos_video1`
    FOREIGN KEY (`video_vidId`)
    REFERENCES `bpmmi5qwcmabqrizkvwa`.`video` (`vidId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_video_has_cargos_cargos1`
    FOREIGN KEY (`cargos_carId`)
    REFERENCES `bpmmi5qwcmabqrizkvwa`.`cargos` (`carId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bpmmi5qwcmabqrizkvwa`.`videoHerramientas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bpmmi5qwcmabqrizkvwa`.`videoHerramientas` (
  `video_vidId` INT(15) NOT NULL,
  `herramientas_herId` INT(15) NOT NULL,
  PRIMARY KEY (`video_vidId`, `herramientas_herId`),
  INDEX `fk_video_has_herramientas_herramientas1_idx` (`herramientas_herId` ),
  INDEX `fk_video_has_herramientas_video1_idx` (`video_vidId` ),
  CONSTRAINT `fk_video_has_herramientas_video1`
    FOREIGN KEY (`video_vidId`)
    REFERENCES `bpmmi5qwcmabqrizkvwa`.`video` (`vidId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_video_has_herramientas_herramientas1`
    FOREIGN KEY (`herramientas_herId`)
    REFERENCES `bpmmi5qwcmabqrizkvwa`.`herramientas` (`herId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
